pipeline {
  agent any
  stages {

    stage('Build') {
      steps {
        echo "Building the war"
      }
    }

    stage("Deploy to QA") {
      steps {
        echo "Deploying to QA"
      }
    }

    stage('Pull Docker Image') {
      parallel {
        stage("Pulling Gorest image") {
          steps {
            bat 'docker pull roopavinmayi/gorestddtest:1.0'
          }
        }
        stage("Pulling Booking API image") {
          steps {
            bat 'docker pull roopavinmayi/bookingapitest:1.0'
          }
        }

      }
    }

    stage('Run API Test Cases') {
      parallel {
        stage("Running GoRest Image") {
          steps {
            bat 'docker run --rm -v "%WORKSPACE%/newman:/app/results" roopavinmayi/gorestddtest:1.0'
          }
        }
        stage("Running Booking API Image") {
          steps {
            bat 'docker run --rm -v "%WORKSPACE%/newman:/app/results" roopavinmayi/bookingapitest:1.0'
          }
        }

      }
    }
    stage('Publish HTML Extra Report') {
      parallel {
        stage("Publish GoRest Report ") {
          steps {
            publishHTML([
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'newman',
              reportFiles: 'gorest.html',
              reportName: 'GoRest API Report',
              reportTitles: ''
            ])
          }
        }
        stage("Publish Booking Report ") {
          steps {
            publishHTML([
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'newman',
              reportFiles: 'booking.html',
              reportName: 'Booking API Report',
              reportTitles: ''
            ])
          }
        }

      }
    }

    stage("Deploy to PROD") {
      steps {
        echo "Deploying to PROD"
      }
    }
  }
}